CREATE TABLE analises_financeiras (

    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    renda_mensal NUMBER(10,2) NOT NULL,

    nivel_endividamento NUMBER(3) NOT NULL,

    frequencia_poupanca VARCHAR2(20) NOT NULL,

    perfil_financeiro VARCHAR2(30),

    probabilidade NUMBER(5,2),

    data_analise TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);