CREATE TABLE transacoes (

    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    descricao VARCHAR2(255) NOT NULL,

    valor NUMBER(10,2) NOT NULL,

    categoria VARCHAR2(30),

    analise_financeira_id NUMBER NOT NULL,

    CONSTRAINT fk_transacao_analise
        FOREIGN KEY (analise_financeira_id)
        REFERENCES analises_financeiras(id)

);