spring.application.name=finance-ai-api

# ==========================
# Configurações do banco de dados Oracle
# ==========================
#spring.datasource.url=jdbc:oracle:thin:@//SEU_HOST:1522/SEU_SERVICE_NAME
#spring.datasource.username=SEU_USUARIO
#spring.datasource.password=SUA_SENHA
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ==========================
# Configurações do Hibernate
# ==========================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Configurações do serviço do FastAPI
# ==========================
#ml.service.url=http://ml-service:8000